spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    clickhouse:
      url: jdbc:clickhouse:http://localhost:8123/pushup
      username: dev
      password: dev1234
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    postgres:
      url: jdbc:postgresql://127.0.0.1:5432/pushup-db
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver


  # Redis configs
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      lettuce:
        shutdown-timeout: 100ms

  # Hibernate dialect for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Automatically update schema (optional)
    hibernate:
      ddl-auto: update
    # Show SQL queries in logs (optional)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka event bus configurations
  # Kafka event bus configurations
  kafka:
    bootstrap-servers: localhost:9097

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: true
        delivery.timeout.ms: 120000
        linger.ms: 5
        enable.idempotence: true

    consumer:
      group-id: shopy-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false

  web:
    error:
      include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,httptrace

  # --- Basic app info ---
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

  # --- Metrics tags (optional but useful) ---
  metrics:
    tags:
      application: my-spring-app

app:
  security:
    jwt:
      SECRET_KEY: aljvnkjn3)n3u4nf9un9u3n59-3inon3v
      ACCESS_TOKEN_VALIDITY_SECONDS: 300000
      REFRESH_TOKEN_VALIDITY_SECONDS: 900000
  clickhouse:
    kafka:
      kafka_num_consumers: 8
      max_block_size: 1000
      kafka_poll_timeout_ms: 500
  kafka:
    partitions: 8
    replicas: 1